#
# Installation & freezing of dependencies for the development version of
# the MaBSharing back end.
#

version: "3.2"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.install
    image: mabsharing-dev/backend
    entrypoint: ["npm", "i"]
    networks:
      - mabsharing-dev
    ports:
      - "10011:26017"
      - "26018:26018"
    volumes:
      - .:/home/mabsharing/server
      - mabsharing-dev_modules:/home/mabsharing/server/node_modules


networks:
  mabsharing-dev:

volumes:
  mabsharing-dev_modules:
    driver: local
