#
# Installation & freezing of dependencies for the development version of
# the MaBSharing back end.
#

#version: "3.2"
version: "2.0"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mabsharing-dev/backend
    entrypoint: ["./node_modules/.bin/nodemon", "--watch", "./src", "--inspect=0.0.0.0:26018", "./src/index.js"]
    environment:
      - PORT=26017
      - NODE_ENV=development
      - SECRET=g7NCMb3UPYGs5zgxzaB45vy3fem4RRTXAxsXj5vXE2Zks7GQ8TvNdEsjJCYs5uef
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mabsharing
      - DB_USER=mabsharing
      - DB_PASSWORD=xWWwqB9yxBjPq4FUcpQxrxMaGkze4Qx29Pp9BT3wg4UgfWLy5VCuAsQ8sJvCf58v
    networks:
      - mabsharing_dev
    ports:
      - "10011:26017"
      - "26018:26018"
    volumes:
      - .:/home/mabsharing/server
      - mabsharing-dev_modules:/home/mabsharing/server/node_modules
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=BDaG5E9tSJj8MBykrGNWTc6YmwwfmRh6383nmprxspCb3m7Ls39k2ttFKGF9VxvU
      - MYSQL_DATABASE=mabsharing
      - MYSQL_USER=mabsharing
      - MYSQL_PASSWORD=xWWwqB9yxBjPq4FUcpQxrxMaGkze4Qx29Pp9BT3wg4UgfWLy5VCuAsQ8sJvCf58v
    networks:
      - mabsharing_dev
    ports:
      - "11011:3306"
    volumes:
        - ./initdb.d:/docker-entrypoint-initdb.d

networks:
  mabsharing_dev:

volumes:
  mabsharing-dev_modules:
    driver: local
